on:
  push:
    branches:
      - main

permissions: write-all

name: Main Release
jobs:
  build:
    name: Create Release
    if: "!startsWith(github.event.head_commit.message, 'release')"
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main
        token: ${{ secrets.REPO_TOKEN }}

    - name: Setup node and yarn
      uses: actions/setup-node@v2
      with:
        node-version: '18.12.0'
        cache: 'yarn'
        registry-url: 'https://registry.npmjs.org'

    - name: Run release script
      run: ./build-scripts/main-release.sh
      env:
        CI: false
        YARN_NPM_AUTH_TOKEN: ${{ secrets.BOT_TOKEN }}
        BOT_EMAIL: jocelyn.mutso@gmail.com 
        BOT_NAME: jocelyn.mutso
        
